// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sut.se.project.domain;

import org.springframework.beans.factory.annotation.Configurable;
import sut.se.project.domain.BillUI;

privileged aspect BillUI_Roo_Configurable {
    
    declare @type: BillUI: @Configurable;
    
}
